eq(1) = equation(cal, @(hat,cal,cSS) (cal.a * hat.g.^(-cal.sigma^-1)) * ...
    (cSS^((cal.sigma^-1) -cal.gamma))   +...
    cal.beta * cal.theta .* hat.fg - hat.f ...
    ,cSS);

eq(2) = equation(cal, @(hat,cal,cSS)...
    (  cal.a  * hat.g.^(-cal.sigma^-1)) * (cSS^((cal.sigma^-1)-cal.gamma)) .* ...
       (1- cal.a* (cal.sigma^-1)* (hat.g - cal.theta * hat.x)./ hat.g ) + ...
    cal.a * cal.beta * cal.theta * (hat.g-cal.theta * hat.x) .* hat.f1g -...
    (1 - cal.beta * cal.theta) ...
    ,cSS);
 
